"""Live transcript generator for engram-mcp.

Spawns scripts/run_mcp_server.py as a real subprocess (stdio transport) and
drives it with the MCP client SDK against the LIVE database configured in
.env: initialize -> list_tools -> call recall -> call get_memory_stats, for
user_id="e2e-prasad" (has real memory + skill data from earlier manual
testing). Writes the full request/response exchange as readable markdown to
docs/mcp-transcript.md — judge-readable proof the protocol path works end
to end, not just that the tool functions pass unit tests in isolation.

Run: python scripts/mcp_demo_transcript.py
"""

from __future__ import annotations

import asyncio
import json
import os
import sys
from datetime import datetime, timezone

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from dotenv import load_dotenv  # noqa: E402

load_dotenv()

DEMO_USER_ID = "e2e-prasad"
DEMO_QUERY = "still life composition"
OUTPUT_PATH = os.path.join(REPO_ROOT, "docs", "mcp-transcript.md")


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def _pretty(obj) -> str:
    return json.dumps(obj, indent=2, default=str)


async def run_transcript() -> list[dict]:
    """Drive the real engram-mcp stdio server and collect one log entry per
    request/response pair. Returns the log; does not write the file (kept
    separate so this stays easy to unit-test later if desired)."""
    from mcp import ClientSession
    from mcp.client.stdio import StdioServerParameters, stdio_client

    # env is passed explicitly because stdio_client's default child env is a
    # sanitized allowlist (HOME/PATH/etc.) that strips MONGODB_URI, and a
    # container has no .env file for the child's own load_dotenv() to find.
    # cwd stays for path resolution of the launcher script and local .env.
    params = StdioServerParameters(
        command=sys.executable,
        args=[os.path.join("scripts", "run_mcp_server.py")],
        env=dict(os.environ),
        cwd=REPO_ROOT,
    )

    log: list[dict] = []

    async with stdio_client(params) as (read, write):
        async with ClientSession(read, write) as session:
            t0 = _now_iso()
            init_result = await session.initialize()
            log.append({
                "timestamp": t0,
                "step": "initialize",
                "request": {},
                "response": {
                    "serverInfo": {"name": init_result.serverInfo.name, "version": init_result.serverInfo.version},
                    "protocolVersion": init_result.protocolVersion,
                },
            })

            t1 = _now_iso()
            tools_result = await session.list_tools()
            log.append({
                "timestamp": t1,
                "step": "list_tools",
                "request": {},
                "response": {
                    "tools": [
                        {"name": t.name, "description": t.description, "inputSchema": t.inputSchema}
                        for t in tools_result.tools
                    ]
                },
            })

            t2 = _now_iso()
            recall_args = {"user_id": DEMO_USER_ID, "query": DEMO_QUERY}
            recall_result = await session.call_tool("recall", recall_args)
            log.append({
                "timestamp": t2,
                "step": "call_tool",
                "tool": "recall",
                "request": recall_args,
                "response": {
                    "isError": recall_result.isError,
                    "content": [json.loads(c.text) for c in recall_result.content],
                },
            })

            t3 = _now_iso()
            stats_args = {"user_id": DEMO_USER_ID}
            stats_result = await session.call_tool("get_memory_stats", stats_args)
            log.append({
                "timestamp": t3,
                "step": "call_tool",
                "tool": "get_memory_stats",
                "request": stats_args,
                "response": {
                    "isError": stats_result.isError,
                    "content": [json.loads(c.text) for c in stats_result.content],
                },
            })

    return log


def render_markdown(log: list[dict]) -> str:
    lines: list[str] = []
    lines.append("# engram-mcp live transcript")
    lines.append("")
    lines.append(
        "Generated by `scripts/mcp_demo_transcript.py` against the LIVE MongoDB "
        "configured in `.env` — a real subprocess speaking the MCP stdio protocol, "
        f"not a mocked call. Demo user: `{DEMO_USER_ID}` (has real memory + skill data "
        "from earlier manual testing)."
    )
    lines.append("")
    lines.append(f"Run at: {log[0]['timestamp']}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for entry in log:
        step = entry["step"]
        ts = entry["timestamp"]
        if step == "initialize":
            lines.append(f"## `initialize` — {ts}")
            lines.append("")
            lines.append("Handshake with the engram-mcp stdio server.")
            lines.append("")
            lines.append("**Response:**")
            lines.append("```json")
            lines.append(_pretty(entry["response"]))
            lines.append("```")
        elif step == "list_tools":
            lines.append(f"## `list_tools` — {ts}")
            lines.append("")
            lines.append("Enumerates the tools this server mounts.")
            lines.append("")
            lines.append("**Response:**")
            lines.append("```json")
            lines.append(_pretty(entry["response"]))
            lines.append("```")
        elif step == "call_tool":
            tool = entry["tool"]
            lines.append(f"## `call_tool: {tool}` — {ts}")
            lines.append("")
            lines.append("**Request arguments:**")
            lines.append("```json")
            lines.append(_pretty(entry["request"]))
            lines.append("```")
            lines.append("")
            lines.append("**Response:**")
            lines.append("```json")
            lines.append(_pretty(entry["response"]))
            lines.append("```")
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    log = asyncio.run(run_transcript())
    markdown = render_markdown(log)
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write(markdown)
    print(f"Wrote transcript to {OUTPUT_PATH} ({len(log)} exchanges)")


if __name__ == "__main__":
    main()
